FROM node:22-alpine as build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.29.4-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 5173
CMD [ "nginx", "-g", "daemon off;" ]